// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful'

export interface IEpisodeFields {
  /** Title */
  title?: string | undefined

  /** Video Link */
  videoLink?: string | undefined

  /** Image */
  image?: Asset | undefined

  /** Quotes */
  quotes?: IQuote[] | undefined
}

export interface IEpisode extends Entry<IEpisodeFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'episode'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IQuoteFields {
  /** Title */
  title?: string | undefined

  /** Snippet */
  snippet?: Asset | undefined
}

export interface IQuote extends Entry<IQuoteFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'quote'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export type CONTENT_TYPE = 'episode' | 'quote'

export type IEntry = IEpisode | IQuote

export type LOCALE_CODE = 'en-US'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US'
